// <auto-generated />
using System;
using MercDevs_ej2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MercDevs_ej2.Migrations
{
    [DbContext(typeof(MercydevsEjercicio2Context))]
    [Migration("20240613060312_ActualizacionCliente")]
    partial class ActualizacionCliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8_general_ci")
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MercDevs_ej2.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idCliente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("Estado")
                        .HasColumnType("int(11)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("IdCliente")
                        .HasName("PRIMARY");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("MercDevs_ej2.Models.Descripcionservicio", b =>
                {
                    b.Property<int>("IdDescServ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idDescServ");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDescServ"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("ServicioIdServicio")
                        .HasColumnType("int(11)")
                        .HasColumnName("Servicio_idServicio");

                    b.HasKey("IdDescServ")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ServicioIdServicio" }, "fk_DescripcionServicio_Servicio1_idx");

                    b.ToTable("descripcionservicio", (string)null);
                });

            modelBuilder.Entity("MercDevs_ej2.Models.Recepcionequipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accesorio")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("CapacidadAlmacenamiento")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("CapacidadRam")
                        .HasColumnType("int(11)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("Grafico")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int(11)");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int(11)");

                    b.Property<string>("MarcaPc")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("ModeloPc")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Nserie")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("NSerie");

                    b.Property<int?>("TipoAlmacenamiento")
                        .HasColumnType("int(11)");

                    b.Property<int?>("TipoGpu")
                        .HasColumnType("int(11)");

                    b.Property<int?>("TipoPc")
                        .HasColumnType("int(11)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCliente" }, "fk_RecepcionEquipo_Cliente1_idx");

                    b.HasIndex(new[] { "IdServicio" }, "fk_RecepcionEquipo_Servicio1_idx");

                    b.ToTable("recepcionequipo", (string)null);
                });

            modelBuilder.Entity("MercDevs_ej2.Models.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idServicio");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("Precio")
                        .HasColumnType("int(11)");

                    b.Property<string>("Sku")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("UsuarioIdUsuario")
                        .HasColumnType("int(11)")
                        .HasColumnName("Usuario_idUsuario");

                    b.HasKey("IdServicio")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UsuarioIdUsuario" }, "fk_Servicio_Usuario_idx");

                    b.ToTable("servicio", (string)null);
                });

            modelBuilder.Entity("MercDevs_ej2.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idUsuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("password");

                    b.HasKey("IdUsuario")
                        .HasName("PRIMARY");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("MercDevs_ej2.Models.Descripcionservicio", b =>
                {
                    b.HasOne("MercDevs_ej2.Models.Servicio", "ServicioIdServicioNavigation")
                        .WithMany("Descripcionservicios")
                        .HasForeignKey("ServicioIdServicio")
                        .IsRequired()
                        .HasConstraintName("fk_DescripcionServicio_Servicio1");

                    b.Navigation("ServicioIdServicioNavigation");
                });

            modelBuilder.Entity("MercDevs_ej2.Models.Recepcionequipo", b =>
                {
                    b.HasOne("MercDevs_ej2.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Recepcionequipos")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("fk_RecepcionEquipo_Cliente1");

                    b.HasOne("MercDevs_ej2.Models.Servicio", "IdServicioNavigation")
                        .WithMany("Recepcionequipos")
                        .HasForeignKey("IdServicio")
                        .IsRequired()
                        .HasConstraintName("fk_RecepcionEquipo_Servicio1");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("MercDevs_ej2.Models.Servicio", b =>
                {
                    b.HasOne("MercDevs_ej2.Models.Usuario", "UsuarioIdUsuarioNavigation")
                        .WithMany("Servicios")
                        .HasForeignKey("UsuarioIdUsuario")
                        .IsRequired()
                        .HasConstraintName("fk_Servicio_Usuario");

                    b.Navigation("UsuarioIdUsuarioNavigation");
                });

            modelBuilder.Entity("MercDevs_ej2.Models.Cliente", b =>
                {
                    b.Navigation("Recepcionequipos");
                });

            modelBuilder.Entity("MercDevs_ej2.Models.Servicio", b =>
                {
                    b.Navigation("Descripcionservicios");

                    b.Navigation("Recepcionequipos");
                });

            modelBuilder.Entity("MercDevs_ej2.Models.Usuario", b =>
                {
                    b.Navigation("Servicios");
                });
#pragma warning restore 612, 618
        }
    }
}
